dark-mode: true

auto-commits: false
show-model-warnings: false
watch-files: true

model: k2
edit-format: diff
map-tokens: 4096
# reasoning-effort: low

# model: oss
# edit-format: whole
# map-tokens: 1024

alias:
  - "ds:openrouter/deepseek/deepseek-chat-v3.1"
  - "k2:openrouter/moonshotai/kimi-k2-0905"
  - "5:openrouter/openai/gpt-5"
  - "5-mini:openrouter/openai/gpt-5-mini"
  - "or-gemini:openrouter/google/gemini-2.5-pro"
  - "or-flash:openrouter/google/gemini-2.5-flash"
  - "oss:ollama_chat/gpt-oss:20b"
  - "qwen:ollama_chat/qwen3-coder:30b"

