dark-mode: true

auto-commits: false
show-model-warnings: false
watch-files: true

model: 5
edit-format: diff
map-tokens: 8192
# map-tokens: 4096
# map-tokens: 2048

# model: oss
# edit-format: whole
# map-tokens: 1024

reasoning-effort: medium

alias:
  - "k2:openrouter/moonshotai/kimi-k2-0905"
  - "ds:openrouter/deepseek/deepseek-chat-v3.2-exp"
  - "claude:openrouter/anthropic/claude-sonnet-4.5"
  - "gcf:openrouter/x-ai/grok-code-fast-1"
  - "g4f:openrouter/x-ai/grok-4-fast"
  - "5:openrouter/openai/gpt-5"
  - "5-mini:openrouter/openai/gpt-5-mini"
  - "oss:ollama_chat/gpt-oss:20b"
  - "lm-oss:lm_studio/gpt-oss-20b-mlx"
  - "qwen:ollama_chat/qwen3-coder:30b"
  - "lm-qwen:lm_studio/qwen/qwen3-coder-30b"

