theme = "tokyonight_charlie"

[editor]
true-color = true
color-modes = true
scrolloff = 10
bufferline = "always"
# rulers = [100]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-k = ":buffer-previous"
C-j = ":buffer-next"
C-q = ":buffer-close"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "read-only-indicator"]
right = ["spinner", "diagnostics", "register", "selections", "position", "total-line-numbers", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
