theme = "tokyonight_charlie"

[editor]
true-color = true
color-modes = true
scrolloff = 10
bufferline = "always"
# rulers = [100]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-k = ":buffer-previous"
C-j = ":buffer-next"
C-q = ":buffer-close"
C-g = ":run-shell-command zellij run -fc -x 7% -y 7% --width 88% --height 86% -- lazygit"
C-e = ":sh zellij run -f -x 7% -y 7% --width 88% --height 86% -- bash ~/.config/yazi-picker.sh"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "read-only-indicator"]
right = ["spinner", "diagnostics", "register", "selections", "position", "total-line-numbers", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
