theme = "tokyonight_charlie"
# theme = "catppuccin_mocha_charlie"

[editor]
true-color = true
# rulers = [100]
color-modes = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-k = ":buffer-previous"
C-j = ":buffer-next"
C-w = ":buffer-close"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "read-only-indicator"]
center = []
right = ["spinner", "diagnostics", "register", "selections", "position", "total-line-numbers", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

